In [10]:
import pandas as pd

In [11]:
import numpy as np

In [14]:
data = {
    'Name':['A', 'B', 'C', 'D'],
    'Marks':[23, None, 32, 84],
    'StudyHours' :[3, 2, 5, None]
}

In [15]:
df = pd.DataFrame(data)

In [16]:
df.isnull().sum()

Name          0
Marks         1
StudyHours    1
dtype: int64

In [17]:
df

  Name  Marks  StudyHours
0    A   23.0         3.0
1    B    NaN         2.0
2    C   32.0         5.0
3    D   84.0         NaN

In [18]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [19]:
df['StudyHours'] = df['StudyHours'].fillna(df['StudyHours'].mean())

In [20]:
q1 = df['Marks'].quantile(0.25)

In [21]:
q3 = df['Marks'].quantile(0.75)

In [22]:
iqr = q3 - q1

In [23]:
lower = q1 - 1.5 * iqr

In [24]:
upper = q3 + 1.5 * iqr

In [25]:
df = df[(df['Marks'] >= lower) & (df['Marks'] <= upper)]

In [27]:
df['StudyHours'] = np.log(df['StudyHours'])

In [28]:
df

  Name      Marks  StudyHours
0    A  23.000000    1.098612
1    B  46.333333    0.693147
2    C  32.000000    1.609438
3    D  84.000000    1.203973