In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['A','B','C','D'],
    'Department': ['IT','IT','COMP','COMP'],
    'Income': [25000,30000,20000,28000],
    'Experience': [2,5,3,6]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  Name Department  Income  Experience
0    A         IT   25000           2
1    B         IT   30000           5
2    C       COMP   20000           3
3    D       COMP   28000           6

In [5]:
df.groupby('Department')['Income'].agg(
    ['mean','median','min','max','std']
)

               mean   median    min    max          std
Department
COMP        24000.0  24000.0  20000  28000  5656.854249
IT          27500.0  27500.0  25000  30000  3535.533906

In [6]:
for d, x in df.groupby('Department'):
    print(d, x['Income'].tolist())

COMP [20000, 28000]
IT [25000, 30000]

In [7]:
df.groupby('Department')['Experience'].describe()

            count  mean      std  min   25%  50%   75%  max
Department
COMP          2.0   4.5  2.12132  3.0  3.75  4.5  5.25  6.0
IT            2.0   3.5  2.12132  2.0  2.75  3.5  4.25  5.0

In [2]:
import pandas as pd

In [3]:
iris = pd.read_csv("iris.csv")

In [4]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
for s in iris['Species'].unique():

    x = iris[iris['Species'] == s].drop('Species', axis=1)

    print("\n", s)

    print(x.describe())

    print(x.quantile([0.25,0.50,0.75]))

 Iris-setosa
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000
         Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  13.25            4.8         3.125          1.400           0.2
0.50  25.50            5.0         3.400          1.500           0.2
0.75  37.75            5.2         3.675          1.575           0.3

 Iris-versicolor
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000
         Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  63.25            5.6         2.525           4.00           1.2
0.50  75.50            5.9         2.800           4.35           1.3
0.75  87.75            6.3         3.000           4.60           1.5

 Iris-virginica
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000
          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  113.25          6.225         2.800          5.100           1.8
0.50  125.50          6.500         3.000          5.550           2.0
0.75  137.75          6.900         3.175          5.875           2.3