In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import LabelEncoder

In [4]:
import pandas as pd

In [3]:
data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [20, 21, None, 22],
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Marks': [85, 90, 88, None]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
df

  Name   Age  Gender  Marks
0    A  20.0    Male   85.0
1    B  21.0  Female   90.0
2    C   NaN  Female   88.0
3    D  22.0    Male    NaN

In [11]:
df.isnull()

    Name    Age  Gender  Marks
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3  False  False   False   True

In [12]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   21.0  87.666667
std     1.0   2.516611
min    20.0  85.000000
25%    20.5  86.500000
50%    21.0  88.000000
75%    21.5  89.000000
max    22.0  90.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     3 non-null      float64
 2   Gender  4 non-null      object
 3   Marks   3 non-null      float64
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes

In [15]:
df.shape

(4, 4)

In [16]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [17]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [18]:
df['Age'] = df['Age'].astype(int)

In [19]:
le = LabelEncoder()

In [20]:
df['Gender'] = le.fit_transform(df['Gender'])

In [21]:
df

  Name  Age  Gender      Marks
0    A   20       1  85.000000
1    B   21       0  90.000000
2    C   21       0  88.000000
3    D   22       1  87.666667

In [25]:
df.dtypes

Name       object
Age         int64
Gender      int64
Marks     float64
dtype: object